// actions for getting user
export const FETCH_USER_INFO_START = 'FETCH_USER_INFO_START'
export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS'
export const FETCH_USER_INFO_FAILURE = 'FETCH_USER_INFO_FAILURE'

// actions for getting user's entries
export const FETCH_USER_ENTRIES_START = 'FETCH_USER_ENTRIES_START'
export const FETCH_USER_ENTRIES_SUCCESS = 'FETCH_USER_ENTRIES_SUCCESS'
export const FETCH_USER_ENTRIES_FAILURE = 'FETCH_USER_ENTRIES_FAILURE'
